number1 =int(input("Enter the first number:"))
number2 =int(input("Enter the second number:"))
print("sum=",number1+number2,",Division=",number1/number2)
print("Is number1 greater than number2?:",number1>number2)
print ("Are number1 and number2 equal?:",number1==number2)
print("Logical AND:",number1>0 and number2>0)
print("Logical OR:",number1>0 or number2>number1)
